const Actions = {
	// User Status
	SET_USER: "SET_USER",
	CLEAR_USER: "CLEAR_USER",

	/// APP SETTINGS
	SET_APPSTATE: "SET_APPSTATE",
	SET_DIRECTION: "SET_DIRECTION",
	SET_LOCALE: "SET_LOCALE",
	SET_DARK_MODE: "SET_DARK_MODE",

	// USER PROFILES
	SET_PROJECT: "SET_PROJECT",
	SET_BOARD_SPRINT: "SET_BOARD_SPRINT",
	SET_SPRINTS_SPRINT: "SET_SPRINTS_SPRINT",
};

export default Actions;
