const Actions = {
	// User Status
	SET_TOKEN: "SET_TOKEN",
	IS_LOGIN: "IS_LOGIN",

	/// APP SETTINGS
	SET_APPSTATE: "SET_APPSTATE",
	SET_DIRECTION: "SET_DIRECTION",
	SET_LOCALE: "SET_LOCALE",
	SET_DARK_MODE: "SET_DARK_MODE",

	// HYFY
	POST_LOGIN: "POST_LOGIN",
	RESET_PASSWORD: "RESET_PASSWORD",
	RESET_PASSWORD_CONFIRM: "RESET_PASSWORD_CONFIRM",
};

export default Actions;
