const Actions = {
	// User Status
	SET_USER: "SET_USER",
	CLEAR_USER: "CLEAR_USER",

	/// APP SETTINGS
	SET_APPSTATE: "SET_APPSTATE",
	SET_DIRECTION: "SET_DIRECTION",
	SET_LOCALE: "SET_LOCALE",
	SET_DARK_MODE: "SET_DARK_MODE",

	// USER PROFILES
	RESET_APP_INFO: "RESET_APP_INFO",
	SET_PROJECT: "SET_PROJECT",
	SET_BOARD_DATA: "SET_BOARD_DATA",
	SET_SPRINTS_DATA: "SET_SPRINTS_DATA",
};

export default Actions;
